name: Build OpenWrt ImageBuilder Official

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip tar gzip qemu-utils mkisofs
          sudo apt -y install build-essential libncurses5-dev unzip gawk git curl jshon

      - name: Set up OpenWrt
        run: |
          git clone https://github.com/ofmodemsandmen/ROOterSource2305 openwrt
          cd openwrt
          mkdir -p ./images
          ./build X86-64

      - name: Build ImageBuilder
        run: |
          make image PROFILE=x86_64 PACKAGES=""

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: official
          files: ./images
          body: |
            OpenWrt Official
